name = "Aeronautics Modpack"
author = "Modmeister"
version = "1.1.6"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "209bab460089cd33f3a7501f214e20536a2f9b6f34232bb6a7ba7a73ee82fa9b"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.228"
