name = "Aeronautics Modpack"
author = "Modmeister"
version = "1.1.6"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "186241763fe57e3ac60b201d5acde4a6e5af6b40c79f25c01a22f392f712ae55"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.228"
