name = "Aeronautics Modpack"
author = "Modmeister"
version = "1.1.6"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "85d9d65885371b281fed35de0e4417d1931878e76eae480de51faa9ee8fb4313"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.228"
